### ISSUE TITLE
[UnityConnectServicesConfig] config is NOT valid, switching to default

### ISSUE THREAD

**Issue by LanikSJ** [game-ci/docker#105]
**Bug description**
An Android build errors out with:
```
[UnityConnectServicesConfig] config is NOT valid, switching to default
```

**How to reproduce**
I'm using editor:2019.4.17f1-android-0 with CI from [unity3d](https://gitlab.com/gableroux/unity3d)
Full build log can be found here: https://pastebin.com/RRB5wGkK

**Expected behavior**
Using the old unity3d images the builds pass.  Since that project isn't maintained it's not possible to keep using those docker containers.

**Additional details**
I see the same error in Windows builds and playmode and testmode stages.

**Comment by webbertakken** [comment]
This is most likely not a bug. Mostly every time when unity outputs "config is NOT valid", it means the config is indeed not valid.

A few things to check:

- all variables are set in your secrets and properly passed to the action (typos happen)
- special characters in your password (known issue with unity)
- in case of private license, provide the `.ulf` file, not the `.alf` file
- in case of pro or other license, make sure you can log in to the unity website and make sure that your license has open seats or actrivations


Please let us know if that does not solve your problem.

**Comment by LanikSJ** [comment]
@webbertakken I've verified as many of the variables as possible and they all check out.  There's no special characters in our password.  We use a pro license we our extension on the license is `.alf`.  I can login to Unity portal no problem.

**Comment by webbertakken** [comment]
Note that `.alf` is the activation license file, not the actual license file.

Note that pro license uses a serial to activate, not the file as per [the documentation](https://game.ci/docs/github/activation)

**Comment by LanikSJ** [comment]
I was able to activate the license already and got the serial number and everything.  I've added it to my GitLab pipeline as well.
![image](https://user-images.githubusercontent.com/12159404/118739193-a5ba7000-b7fd-11eb-8348-9f5161e69dec.png)

**Comment by webbertakken** [comment]
It looks like you followed both the personal activation flow as well as the professional activation flow. This will not work; you should follow only the professional activation flow.

Internally when you have UNITY_LICENSE set, it will skip the activation flow of pro licenses, which are serial based.

Both workflows are used by many users. There are no known bugs.
