### ISSUE TITLE
Issue with UNITY_LICENSE

### ISSUE THREAD

**Issue by Soshius** [game-ci/docker#107]
**Bug description**
Hi,
I think i have an issue with the license file.
Log : 
UNITY_LICENSE_STANDALONEWINDOWS64 env var not found, using default UNITY_LICENSE env var
Writing UNITY_LICENSE to license file /root/.local/share/unity3d/Unity/Unity_lic.ulf
.
.
.
LICENSE SYSTEM [2021428 21:18:41] License XML document is null
LICENSE SYSTEM [2021428 21:18:41] DOMDocument is NULL
LICENSE SYSTEM [2021428 21:18:41] Unity license information is invalid.

I have set my UNITY_LICENSE variable with the content of the licence generated using https://license.unity3d.com/manual/

I'm using unityci/editor:2020.3.4f1-windows-mono-0.12

I dont really know how i can give more details

**Comment by webbertakken** [comment]
Could you try to use the 0.11 image? It might be related to the latest update to the docker image, but I'm not sure.

**Comment by Soshius** [comment]
Ok i think i resolved my issue ... i added the UNITY_LICENSE variable with type File instead of Variable. I just switched to variable and it seams to work perfectly.

[LicensingClient] Licenses updated successfully

LICENSE SYSTEM [2021428 22:22:21] Next license update check is after 2021-04-29T21:14:41

LICENSE SYSTEM [2021428 22:22:21] Current license is already valid and activated. Skipping license activation process (Provided username/password will be ignored).

Thanks for you quick reply !
