### ISSUE TITLE
Builds taking too long

### ISSUE THREAD

**Issue by Hugo-Pereira** [game-ci/docker#125]
**Bug description**

The build step takes too long. My project is relatively small, but when building on CI, it sometimes takes more than 2 hours. On my machine it takes less than 10 minutes to build.
I get lots of messages like the following int he logs:
```
Start importing Packages/com.unity.collab-proxy/Editor/Collaborate/Assets/Icons/clear-light@2x.png using Guid(c84258b6921bcce45a57f68a07b2143f) Importer(-1,00000000000000000000000000000000)  -> (artifact id: '58f440790c5704270976d00709834f9a') in 0.003114 seconds 
Start importing Assets/Oculus/SampleFramework/Usage/HandsTrainExample/TrainScene/Lightmap-38_comp_light.exr using Guid(c89369294e3e2b243a0856c19795596c) Importer(-1,00000000000000000000000000000000)  -> (artifact id: 'dc66a3f769d56d5aa94ac14bddb262b7') in 0.708070 seconds 
Start importing Packages/com.unity.render-pipelines.universal/Editor/2D/Resources/SceneViewIcons/FreeformLight.png using Guid(c89564426827c76479d8772adb43e6e4) Importer(-1,00000000000000000000000000000000)  -> (artifact id: 'b4c8ca1f3aa811491e143bdb76be6fbb') in 0.350135 seconds 
Start importing Assets/Oculus/Avatar/Samples/SocialStarter/Assets/Textures/Help.png using Guid(c8f5462cc092d0c40ad71773132863e0) Importer(-1,00000000000000000000000000000000)  -> (artifact id: '1b97aaf7311adb338eb7acfccc266a59') in 0.678056 seconds 
Start importing Packages/com.unity.collab-proxy/Editor/PlasticSCM/Assets/Images/d_step1@2x.png using Guid(c8a69ecdf54ac8e4b873466605de27ff) Importer(-1,00000000000000000000000000000000)  -> (artifact id: 'b26cb42f7f0d92860de76c444e4a0d86') in 0.002670 seconds
```

**How to reproduce**

I followed the instructions on how to setup the CI on gitlab.

**Expected behavior**

Expect the cache to be used, and for the jobs to take less than 10 minutes to build consistently.

**Additional details**

These are my cache settings 

```.cache: &cache
  cache:
    key: "$CI_PROJECT_NAMESPACE-$CI_PROJECT_NAME-$CI_COMMIT_REF_SLUG-$TEST_PLATFORM"
    paths:
      - $UNITY_DIR/Library/
      - $UNITY_DIR/Temp/
 ```
      
I didn't have the Temp folder initially, but I added in the hopes of it fixing the issue. No dice.

Thanks in advance

**Comment by webbertakken** [comment]
We have working builds using this image that take a fraction of the time that you described. For example [unity-actions](https://github.com/game-ci/unity-actions/actions/workflows/main.yml).

Your example Looks like GitLab syntax to me. Have you tried the [example project](https://github.com/game-ci/unity3d-gitlab-ci-example-mirror) without modifications?

As this bug has little to do with the docker image I will close this bug report.

**Comment by zpxp** [comment]
Did you fix this? Our docker builds take 6+ hours but build locally using the same script in 30 seconds
