### ISSUE TITLE
Request: UWP windows based image

### ISSUE THREAD

**Issue by almoga296** [game-ci/docker#140]
I want to add my CI generation of .appx for Hololens2 Microsoft headset.
Maybe you have it on your docker images development roadmap?

Almog

**Comment by webbertakken** [comment]
We're close to releasing images and modified actions for Windows, UWP, XBox and Hololens support.

Please see #windows-images on the community discord server for progress on this topic.

**Comment by davidmfinol** [comment]
Closing this issue, as Windows images are now available.
Created this issue to track documentation for them: https://github.com/game-ci/documentation/issues/239
