### ISSUE TITLE
Step 15/15 : RUN choco install git [...] 'choco' is not recognized as an internal or external command,

### ISSUE THREAD

**Issue by GabLeRoux** [game-ci/docker#154]
**Bug description**

Windows based docker images are failing to build due to missing `choco` in base windows image since `v0.17.0` release. For every new Unity version, jobs like [this one](Retry unityci/editor (universal-windows-platform) ) are failing to build.

This bug was introduced by #149. The base image was updated to include `choco` so it seems that no code needs to be updated. We probably only have to release `v0.18.0` in order to fix this error in the actions by publishing new base images and let the new images build themselves. 🚀

**Comment by davidmfinol** [comment]
Images are being successfully built with v0.17.2, so closing this issue.
