### ISSUE TITLE
How to make a image include android and windows-mono or else?

### ISSUE THREAD

**Issue by wolfired** [game-ci/docker#169]
in my case, some resource need to be handle in windows platform, and then build android apk, so i need a image include two platform

**Comment by webbertakken** [comment]
You have two options here:

- Generate a custom image that's passing multiple target platforms. The Editor Dockerfile takes the [module](https://github.com/game-ci/docker/blob/c9850c8241e250b2d4d805260167d795707fe149/images/ubuntu/editor/Dockerfile#L16) argument which can take multiple values. We'd recommend to fork this repository so you can pass this argument either by creating a new workflow or adapting [new-ubuntu-post-2019-2-editor-image-requested.yml](https://github.com/game-ci/docker/blob/main/.github/workflows/new-ubuntu-post-2019-2-editor-image-requested.yml) to take manual or hardcoded arguments. 
- Make your projects target platforms self-contained, i.e. not dependent on other target platform module installations.

**Comment by davidmfinol** [comment]
I'd be curious to know why you would need windows build support while building an Android APK, as I'm wondering if this is something that would apply to other users.
Are you able to share why you want this image?

**Comment by wolfired** [comment]
> I'd be curious to know why you would need windows build support while building an Android APK, as I'm wondering if this is something that would apply to other users. Are you able to share why you want this image?

emm, i was curious too, so i check the build script again and find a bug, so forget it.
