### ISSUE TITLE
Android NDK missing in 2019.4.40f1

### ISSUE THREAD

**Issue by vaind** [game-ci/docker#182]
The 2019.4.40f android image is built incorrectly: https://github.com/game-ci/docker/runs/6927790971?check_suite_focus=true#step:12:7674
```
#9 308.7 Progress:
#9 308.7 [2019.4.40f1 - Android SDK Platform Tools] installed successfully.
#9 308.7 [2019.4.40f1 - Android SDK & NDK Tools] installed successfully.
#9 308.7 [2019.4.40f1 - Android Build Support] installed successfully.
#9 308.7 [2019.4.40f1 - OpenJDK] installed successfully.
#9 308.7 [2019.4.40f1 - Android NDK] failed to download. Error given: Request timeout
#9 308.7 [2019.4.40f1 - Android SDK Platforms 29] installed successfully.
#9 308.7 [2019.4.40f1 - Android SDK Platforms 30] installed successfully.
#9 308.7 [2019.4.40f1 - Android SDK Build Tools] installed successfully.
#9 308.7 Completed with errors.
#9 DONE 312.7s
```

> [GabLeRoux [Totema] — Today at 5:05 PM](https://discord.com/channels/710946343828455455/710946344264794218/988459465739210772)
> Interesting, I would have thought that the exit code would fail the image build, that's interesting. Let's create an issue in the docker repo, there are two things to fix:
> 1. Fail the build when Android SDK or NDK download does a request timeout
> 2. Republish editor-ubuntu-2019.4.40f1-android-1.0.1 due to Android SDK or NDK download request timeout issue

**Comment by webbertakken** [comment]
A rebuild is happening here: https://github.com/game-ci/docker/actions/runs/3210500851/jobs/5247988137

**Comment by webbertakken** [comment]
Proof:
![image](https://user-images.githubusercontent.com/20756439/194709412-34624f6e-b3e9-49f1-a283-7f5938b53a79.png)
