### ISSUE TITLE
unityci/editor:ubuntu-2022.1.17f1-webgl-1 is missing in Docker registry

### ISSUE THREAD

**Issue by cadesalaberry** [game-ci/docker#185]
I see that the version 2022.1.16.f1 has its docker images built, but not the version 2022.1.17f1.

What can I do do contribute and have it pushed to the [docker hub](https://hub.docker.com/r/unityci/editor/tags?page=1&name=2022.1.17)?

It seems that there is a Github action to run to add a new version, but I can't run it on my side.

**Comment by webbertakken** [comment]
It's completely run automatically. It seems that there have been a few failures that require the attention of a core developer. I'll have a look in the coming week(end).

There's no other steps to support 2022.1.17f1.

For image status see our [image status page](https://game.ci/docs/docker/versions).

**Comment by webbertakken** [comment]
Leaving this open until resolved.

**Comment by cadesalaberry** [comment]
Mmm, the new version [`editor-2022.1.18f1-1.0.1`](https://game.ci/docs/docker/versions) which was [released today](https://unity3d.com/unity/whats-new/2022.1.18) also seems to be stuck

**Comment by zh99998** [comment]
`editor-2021.3.11f1-1.0.1` is stuck too.

**Comment by webbertakken** [comment]
Automated pipeline for building the images has been restored. Expect your images in the coming 24 hours.
