### ISSUE TITLE
Cannot build untitled scene

### ISSUE THREAD

**Issue by isole** [game-ci/docker#196]
Happens with 1.0.0 and 1.0.1 with Unity versions 2021.3.15f1 and 2021.3.16f1. We are using GitLab and as a build command we are using [this](https://gitlab.com/game-ci/unity3d-gitlab-ci-example). The project is a default 3D one with a sample scene already in the scene settings. Locally builds fine with the previous mentioned unity versions.

```
Cannot build untitled scene.

(process:116): Gdk-CRITICAL **: 13:55:16.179: gdk_display_beep: assertion 'GDK_IS_DISPLAY (display)' failed
Unloading 0 Unused Serialized files (Serialized files now loaded: 0)
Unloading 22 unused Assets / (0 B). Loaded Objects now: 3763.
Memory consumption went from 82.0 MB to 82.0 MB.
Total: 4.576912 ms (FindLiveObjects: 0.283580 ms CreateObjectMapping: 0.260173 ms MarkObjects: 3.972945 ms  DeleteObjects: 0.059577 ms)
```

Works fine with 0.17.2 and older unity versions, i.e. 2020.1.13f1.

[error-logs.txt](https://github.com/game-ci/docker/files/10260353/error-logs.txt)

**Comment by Div-Inworld** [comment]
Having the same issue with 2021.3.19f1
Any solutions/updates?

**Comment by davidmfinol** [comment]
I looked up this error message in previous issues, and I found this: https://github.com/game-ci/unity-request-activation-file/issues/85#issuecomment-1126089965

In particular, this was cause:
![image](https://user-images.githubusercontent.com/1088474/222934133-177364dc-b215-4ed4-8246-f674b4a07dbf.png)

Can you confirm that the link to the scene is still intact if you open a fresh clone of your project?

**Comment by isole** [comment]
Indeed, cloning the project again and opening a fresh copy the scene is deleted. Exactly as @davidmfinol described.

**Comment by isole** [comment]
Seems that 2021.3.20f1 is also affected. Upgraded to that version, cloned a fresh copy opened the project locally and the scene is still shown as deleted.

**Comment by felipeViana** [comment]
Hi, any updates on how to solve this?
I'm having this error on Unity 2023.1.3f1

**Comment by felipeViana** [comment]
> Hi, any updates on how to solve this? I'm having this error on Unity 2023.1.3f1

Solved! Just needed to click on `Add Open Scenes`.

**Comment by REgorion** [comment]
Even after clicking the "Add Open Scenes" button and reopening the project, nothing changed.
The list of scenes is still empty
![image](https://github.com/game-ci/docker/assets/26139328/29080556-89a9-4d4e-9505-837d7d710aca)
Same thing happens with project settings, after making any changes I see nothing in git status
Has anyone encountered anything like this?

**Comment by webbertakken** [comment]
I've had that issue once as well. What I did to solve it was add the scenes and then run a local build. Finally restart the editor. The file was then adjusted.

**Comment by atb-brown** [comment]
I had trouble finding this `Add Open Scenes` option, but it's in the [Build Settings](https://docs.unity.com/qnx/en/manual/Build%20Settings) (`File` > `Build Settings...` on Mac).

**Comment by sybaris** [comment]
Hi

I have this issue "Cannot build untitled scene" on my pipeline.
https://github.com/MrGautier256/Jeux-Video-Gaias-Guardian/actions/runs/14156582111/job/39656612219
Help would be appreciated

Regards
Sybaris

**Comment by webbertakken** [comment]
This issue has been asked and answered. 
Please read the available solutions that were offered above. There is no indication of why they wouldn't work.

If for any reason they do not work for you, please create a new issue
