### ISSUE TITLE
Add support for Unity 2023.1

### ISSUE THREAD

**Issue by viitana** [game-ci/docker#201]
**Context**

Unity 2023.1 has entered beta. These versions contain critical bugfixes for my team's project but we are unable to transition as there are currently no 2023.1 based images for `unityci/editor`.

Is it realistic to add support for 2023.1 right now or is this something that would have to wait until stable? If I recall correctly there's previously been image tags available for beta and alpha Unity versions even.

**Suggested solution**

Start building and publishing images for Unity 2023.1 beta.

**Comment by AndrewKahr** [comment]
I don't think this project has ever offered beta images in the past. I do agree though that once editors hit beta it would be nice to have automatically built images as this would make it easier to develop on beta versions but also help gameci notice any incompatibilities before they hit release versions. I think the concern was it breaking pipelines for excessive failures. Perhaps more backend changes are needed to be more lenient on beta errors.

As a stop gap though you can build your own docker image and use that via the customImage parameter.

**Comment by MrGadget1024** [comment]
As a producer of a library on the asset store for Unity, we'd appreciate having beta images to run our tests against. Technically we only support LTS releases of Unity, but it would be nice to know about breaking changes that Unity has implemented for planning purposes. We currently run nearly 1000 unit tests against a matrix of four Unity versions (2019, 2020, 2021, and 2022). If a beta release image was available, we'd set up a separate workflow for that and just report the results to our internal team.

**Comment by tajima-yahoo** [comment]
I found an alternative project from the fork that supports alpha/beta versions.
https://github.com/mob-sakai/docker

### Docker Images

https://hub.docker.com/r/mobsakai/unity3d/tags

### Usage

Use `customImage: mobsakai/unity3d:{version}-{module}` option.

```
- uses: game-ci/unity-test-runner@v2
  with:
    customImage: mobsakai/unity3d:2020.3.0f1-webgl
    ...
```
