### ISSUE TITLE
Support for Windows Server 2022

### ISSUE THREAD

**Issue by mschultz-aofl** [game-ci/docker#213]
**Context**

Windows Server 2019 (1809) will be EOL in about 6 months. Attempting to run a Windows-based Editor container in Windows Server 2022 returns 
`ERROR: Job failed (system failure): Error response from daemon: hcs::CreateComputeSystem 495d65b4034d0510367c8c9daa8a60ff46591a2653d5aebe4e6921620e3f0e40: The container operating system does not match the host operating system. (exec.go:78:0s)`

**Suggested solution**

Add support for Windows server 2022 in the Base template - It's unclear if we need to support both going forward, or if we should simply stop supporting Win2019 as MS is doing

**Considered alternatives**

Not really one, unless we want to keep using an EOL OS for il2cpp builds

**Additional details**

https://learn.microsoft.com/en-us/lifecycle/products/windows-server-2019

**Comment by AndrewKahr** [comment]
Images are now Server 2022 in v3
