### ISSUE TITLE
manifest for unityci/editor:2022.3.8f1-linux-il2cpp-1 not found

### ISSUE THREAD

**Issue by RevenantX** [game-ci/docker#221]
Seems that 2022.3.8f1 doesn't exists in dockerhub https://hub.docker.com/r/unityci/editor

**Comment by webbertakken** [comment]
As you've seen in my answer the help thread on Discord already: The image isn't published yet.

This image is so new that Unity hasn't even published the version on [their own website](https://unity.com/releases/editor/archive) yet.
