### ISSUE TITLE
manifest for unityci/editor:windows-2021.3.16f1-webgl-2 not found

### ISSUE THREAD

**Issue by BFS-JWesseler** [game-ci/docker#222]
**Bug description**

Getting the following error: manifest for unityci/editor:windows-2021.3.16f1-webgl-2 not found

**How to reproduce**

- Use the game-ci/unity-builder@v3 on GitHub on windows-latest for Unity version 2021.3.16f1.

**Expected behavior**

**Additional details**

**Comment by webbertakken** [comment]
That's because the WebGL image runs on Ubuntu.

`editor-ubuntu-2021.3.16f1-webgl-2` is available as normal.
