### ISSUE TITLE
Error when pulling ci editor image for version 2022.3.29.f1

### ISSUE THREAD

**Issue by User1Jazz** [game-ci/docker#246]
**Bug description**

Attempting to use the CI for Unity version 2022.3.29f1 resolves with errors when trying to pull the editor docker image. It seems like the defined version image does not exist.

**How to reproduce**

Create or open the existing Unity project using Unity version 2022.3.29f1 
Commit and push changes
Wait for CI to build the project

**Expected behavior**

CI should be able to pull the image of the defined version.

**Additional details**

`ERROR: Job failed: failed to pull image "unityci/editor:2022.3.29f1-base-1" with specified policies [always]: Error response from daemon: manifest for unityci/editor:2022.3.29f1-base-1 not found: manifest unknown: manifest unknown (manager.go:250:1s)`

**Comment by GabLeRoux** [comment]
You can have a look here:
https://game.ci/docs/docker/versions

The unity version is present, you might have to update your pipelines and yaml code. The latest docker project version is 3 at this time, yours end in `-1`, we don’t publish older versions of the Dockerfile anymore.

See https://github.com/game-ci/docker/releases for more details about the versions of the Dockerfile.

If you’re using github actions, you need to use latest actions versions. If you’re trying on GitlabCI, you’ll have to update the version on your own for now.

Feel free to provide additional details and workflow files if you need some help.

**Comment by User1Jazz** [comment]
I am using GitLab. Changing the image version to the latest one (3.1.0) fixed the problem.
Thanks.
