### ISSUE TITLE
Missing version 2022.3.44f1

### ISSUE THREAD

**Issue by saez0pub** [game-ci/docker#250]
**Bug description**

Attempting to use the last LTS version 2022.3.44f1 is failing because the docker image does not exists.

**How to reproduce**

* Create a project with an editor version 2022.3.44f1
* setup github action with a build
```yaml
      - name: Build project
        uses: game-ci/unity-builder@v4
``` 
You get this error:
> Unable to find image 'unityci/editor:ubuntu-2022.3.44f1-webgl-3' locally
> docker: Error response from daemon: manifest for unityci/editor:ubuntu-2022.3.44f1-webgl-3 not found: manifest unknown: manifest unknown.
> See 'docker run --help'.

**Expected behavior**

Build success

**Additional details**

I checked https://game.ci/docs/docker/versions/ and the last version available is editor-ubuntu-2022.3.42f1-webgl-3.1.0

My version is tagged LTS: https://unity.com/releases/editor/archive

**Comment by webbertakken** [comment]
Seems like we're missing 2022.3.43, 44, 45.
I'm also observing that the latest 6000.0.17f1 did actually make it. The same for 2023.2.20f1.

Might be related to https://github.com/game-ci/versioning-backend/pull/51 and https://github.com/game-ci/versioning-backend/pull/52 or otherwise due to a change on the unity downloads [archive page](https://unity.com/releases/editor/archive). I looked into both PRs but nothing stands out to me. Perhaps @AndrewKahr?

Backend reports a few failed builds for 2021.3.40f1 and 2021.3.39f1. I have reset the retry count for them to 0. They are rebuilding:

- https://github.com/game-ci/docker/actions/runs/10701259216
- https://github.com/game-ci/docker/actions/runs/10701259236

So far no clear idea as to why 2022.3.x are not being triggered to build by the versioning backend.

**Comment by saez0pub** [comment]
I've tested manually the archive [regexp](https://github.com/game-ci/versioning-backend/blob/main/functions/src/logic/ingestUnityVersions/scrapeVersions.ts).

```shell
curl -s https://unity.com/releases/editor/archive | perl -nle'print $& while m/unityhub:\/\/(\d+)\.(\d+)\.(\d+[a-zA-Z]\d+)\/(\w+)/g' | grep 2022.3.4 | sort -u

unityhub://2022.3.40f1/cbdda657d2f0
unityhub://2022.3.41f1/0f988161febf
unityhub://2022.3.42f1/2dcb6a0abc42
unityhub://2022.3.43f1/85497d293fa1
unityhub://2022.3.44f1/c3ae09b9f03c
unityhub://2022.3.45f1/a13dfa44d684
unityhub://2022.3.4f1/35713cd46cd7
``` 

It seems the download page returns something compatible.

**Comment by AndrewKahr** [comment]
I unfortunately don't have bandwidth to dig deep into this currently but I did notice that we have some build failures on 2021. Perhaps those need to be fixed first? It could be clogging up the pipeline from too many failures. Though I'm not sure why 6000 versions would build from that hypothesis. I think the 2021 fix is just an android path that needs updating so might be worth starting there as it should be straightforward.

The scraping logic lives here if anyone wants to investigate that to validate the regex works on the page we are targeting: https://github.com/game-ci/versioning-backend/blob/main/functions/src/logic/ingestUnityVersions/scrapeVersions.ts

**Comment by GoatHunter** [comment]
Hi, is there a way I can contribute to solving this, we're all stalled (wanting to upgrade to versions higher than 2022.3.42)

Any pointers on how to get started will be awesome, thanks beforehand!

**Comment by webbertakken** [comment]
On [our discord](https://game.ci/discord) there's additional details, in [this channel](https://discord.com/channels/710946343828455455/1280995422135123988). No fix yet.

**Comment by viglucci** [comment]
Hi @webbertakken thanks for the links. It seems like the channel link points to the Welcome channel, is there a different link?

**Comment by MrGadget1024** [comment]
> Hi @webbertakken thanks for the links. It seems like the channel link points to the Welcome channel, is there a different link?

On the Discord server, go to help channel, click threads button, search for a thread called "2022.3.3 images are not being built..."
Direct channel link: https://discord.com/channels/710946343828455455/1280995422135123988

**Comment by TCGXR** [comment]
PLEASEEEEEEEEEEEEEEEEEEEEEE!

**Comment by GabLeRoux** [comment]
I just wrote [a message](https://discord.com/channels/710946343828455455/1280995422135123988/1291422548503826443) about this issue in the related discord thread. Writting it here as well so more people can help:

> The last bits of information we have concerning this problem according to [this message from Webber](https://discord.com/channels/710946343828455455/1280995422135123988/1285311225277710346) is:
> 
> 1. `2022.3.43f1` was never ingested
> 2. The problem would be somewhere in [game-ci/versioning-backend's `functions/src/logic/buildQueue`](https://github.com/game-ci/versioning-backend/tree/main/functions/src/logic/buildQueue)
> 3. All versions after `2022.3.43f1` are not being ingested
> 
> The best way to investigate this is most likely to:
> 1. Follow the [development guide (updated one)](https://github.com/game-ci/versioning-backend/blob/4a32fb652f1c59638ba7abb4cdec753000b906c3/DEVELOPMENT.md)
> 2. Provide [feedback about that updated development guide](https://github.com/game-ci/versioning-backend/pull/53) so we can have as many people as possible able to work on this project
> 3. Figure out why [`ingeminator.ts`](https://github.com/game-ci/versioning-backend/blob/main/functions/src/logic/buildQueue/ingeminator.ts) is not retrieving versions `2022.3.x` anymore (if that is the case).

**Comment by GabLeRoux** [comment]
>  Also worth noting that the issue also affects all versions after 2021.3.43f1

**Comment by MrGadget1024** [comment]
Fixed by https://github.com/game-ci/versioning-backend/pull/54

**Comment by TCGXR** [comment]
Thank you some much!
