### ISSUE TITLE
Missing 2022.3.46f1 image version from docker hub

### ISSUE THREAD

**Issue by VoldarGames** [game-ci/docker#251]
**Bug description**

The Unity 2022.3.46f1 image version is missing from Docker Hub. This version cannot be found when attempting to pull or search for it.

**Expected behavior**

Unity version 2022.3.46f1 is part of the Unity LTS releases and should have an available image for CI/CD pipelines.

Thanks in advance!!

**Comment by webbertakken** [comment]
Please follow https://github.com/game-ci/docker/issues/250

**Comment by VoldarGames** [comment]
Thanks! Also for your effort maintaining this project

**Comment by MrGadget1024** [comment]
Fixed by https://github.com/game-ci/versioning-backend/pull/54
