### ISSUE TITLE
Building for il2cpp StandaloneLinux64 and webgl fails with 'Could not find valid clang executable at clang'

### ISSUE THREAD

**Issue by GabLeRoux** [game-ci/docker#53]
Linking the following gitlab issue which has more details:  
https://gitlab.com/gableroux/unity3d-gitlab-ci-example/-/issues/139

I think this needs to be solved in here, but I don't have any clue on what to do. Help is greatly appreciated.

**Comment by GabLeRoux** [comment]
Solution found by Andreas Knote:  
https://gitlab.com/gableroux/unity3d-gitlab-ci-example/-/issues/139#note_462310425

We need to add these packages to docker image:  
* python
* python3 
* clang
* build-essential

Question is: should we add these to base image or specific `WebGL` and `Linux IL2CPP`?

**Comment by webbertakken** [comment]
Do we indeed need both python 2 and 3?

As these deps are really small (together under 2 meg from what I saw, which is acceptable in 1GB+ images) and may be commonly needed I'd argue to put them in the base image.

**Comment by GabLeRoux** [comment]
I'm a python fanboy so +1 for base image, they're indeed quite small:

|package                                           |installed size amd64|
|--------------------------------------------------|--------------------|
|https://packages.ubuntu.com/xenial/python         | 635.0 kB           |
|https://packages.ubuntu.com/xenial/python3        |67.0 kB             |
|https://packages.ubuntu.com/xenial/clang          |28.0 kB             |
|https://packages.ubuntu.com/xenial/build-essential|20.0 kB             |
|Total|750.0 kB             |

I don't know if it's how we should calculate package sizes when using docker, but it sure looks small.

**Comment by webbertakken** [comment]
🐍🧔

Yea that's installed size, but I believe it becomes compressed when pushing the images.

Not sure if we need any dependencies with that?

**Comment by dharmeshmp** [comment]
![Screenshot 2020-12-12 at 10 32 02 AM](https://user-images.githubusercontent.com/8749772/101975875-fb468b80-3c65-11eb-8bf4-67e86d20616e.png)

I have calculated the image size after installing it in the machine by following the method.
`root@ubuntu-s-4vcpu-8gb-blr1-01:~# docker run -it unityci/editor:2020.1.16f1-webgl-0.7 bash`
`root@e386fb0a83b3:/# apt update`
`root@e386fb0a83b3:/# apt install clang`
`root@e386fb0a83b3:/# exit`
`root@ubuntu-s-4vcpu-8gb-blr1-01:~# docker ps -a`

```
CONTAINER ID        IMAGE                                  COMMAND             CREATED              STATUS                     PORTS               NAMES
e386fb0a83b3        unityci/editor:2020.1.16f1-webgl-0.7   "bash"              About a minute ago   Exited (0) 7 seconds ago                       affectionate_liskov

```

`root@ubuntu-s-4vcpu-8gb-blr1-01:~# docker commit e386fb0a83b3 unityci/editor:2020.1.16f1-webgl-0.7-with-clang`

I don't know this is the proper way to check the size but if I am right then you can see the result above.

Also, I have tested by adding the only `clang` to WebGL and it will successfully build. Not tested other platforms.

I hope this will help.

**Comment by webbertakken** [comment]
We usually install using `apt-get -q install -y --no-install-recommends --allow-downgrades` in the [base image](https://github.com/game-ci/docker/blob/main/base/Dockerfile).

Best case scenario that would make the size difference a lot smaller. Throwing 400 megs on top is a bit much for the clang compiler I feel, let alone another 3 gigs for python.

**Comment by cocor-au-lait** [comment]
Hi, I'm using this image to build WebGL app.
I tentatively added extra build script to install `python2` to avoid emscripten build errors.
https://github.com/cocor-au-lait/docker/commit/9fb5e91248f21bd49ddb9b8ce12c06377c9f6998
I think for WebGL building, the only additional package required was `python2`

**Comment by webbertakken** [comment]
Will be in v0.9
