### ISSUE TITLE
error: libunwind.so.8: cannot open shared object file: No such file or directory (2019.1.x)

### ISSUE THREAD

**Issue by mob-sakai** [game-ci/docker#57]
**Bug description**

When I start a Unity project on `unityci/editor:2019.1.***-***-0`, it exits with compilation errors.

```
-----CompilerOutput:-stderr----------
Failed to load H��, error: libunwind.so.8: cannot open shared object file: No such file or directory
Failed to bind to CoreCLR at '/opt/unity/Editor/Data/Tools/Roslyn/libcoreclr.so'
```

Full log: [log](https://github.com/game-ci/docker/files/5806925/createProject.log)

**How to reproduce**

1. In the directory where `Unity_v*.ulf` (for machine ID `576562626572264761624c65526f7578`) exists, run the following command:
```sh
UNITY_LICENSE=$(cat Unity_v*.ulf)
docker run --rm -v "$(pwd)":/logs -w /home -i unityci/editor:2019.1.14f1-base-0 bash <<EOF
echo '$UNITY_LICENSE' > ulf
unity-editor -logFile /logs/manualLicenseFile.log -quit -nographics -manualLicenseFile ulf
unity-editor -logFile /logs/createProject.log -quit -nographics -createProject ./TestProject
EOF
```

2. See `createProject.log`

**Expected behavior**

Compilation completed successfully.

**Additional details**

In 2019.1, the following libraries are required.
* libnotify4
* libunwind-dev
* libssl1.0

Like this:
```dockerfile
# add dependencies
RUN [ `echo $version | grep -v '^2019.1.'` ] && exit 0 || : \
  && apt-get -q update \
  && apt-get -q install -y --no-install-recommends --allow-downgrades \
    libnotify4 \
    libunwind-dev \
    libssl1.0  \
  && apt-get clean \
  && rm -rf /var/lib/apt/lists/*
```

**Comment by webbertakken** [comment]
Looks good. Feel free to submit it as a PR!

**Comment by mob-sakai** [comment]
No.
As far as I can tell, this issue only occurs in `2019.1.x`.

**Comment by HmSebastianH** [comment]
I think im encountering the same issue on 2019.4

**Comment by webbertakken** [comment]
> I think im encountering the same issue on 2019.4

Did you try to apply the same fix in a custom image, based on the editor image we provided?

**Comment by HmSebastianH** [comment]
> > I think im encountering the same issue on 2019.4
> 
> Did you try to apply the same fix in a custom image, based on the editor image we provided?

So I actually just found the time to try this and yes, build for 2019.4.21f was fixed by adding above code (without the conditional ofc.)
