### ISSUE TITLE
Android support for Unity 2019.2 or earlier

### ISSUE THREAD

**Issue by mob-sakai** [game-ci/docker#68]
**Context**

Add support Android module for Unity 2019.2 or earlier.

**Suggested solution**

Install Android SDK and tools at `editor/Dockerfile` for Unity 2019.2 or earlier.

Like this:

```dockerfile
#=======================================================================================
# [2018.x-android] Install Android SDK/JDK
#=======================================================================================
RUN [ `echo $version-$module | grep -v '^2018.*-android'` ] && exit 0 || : \
  \
  # Environment Variables
  # 2018.3.0f2: https://gitlab.com/gableroux/unity3d/-/blob/master/ci-generator/unity_versions.old.yml#L4344
  && export ANDROID_BUILD_TOOLS_VERSION=29.0.3 \
  && export ANDROID_CMD_LINE_TOOLS_VERSION=6609375 \
  && export ANDROID_NDK_VERSION=16.1.4479499 \
  && export ANDROID_PLATFORM_VERSION=29 \
  \
  # Environment Variables
  && export ANDROID_INSTALL_LOCATION=${UNITY_PATH}/Editor/Data/PlaybackEngines/AndroidPlayer \
  && export ANDROID_SDK_ROOT=${ANDROID_INSTALL_LOCATION}/SDK \
  && export ANDROID_HOME=${ANDROID_SDK_ROOT} \
  && export ANDROID_NDK_HOME=${ANDROID_INSTALL_LOCATION}/NDK/${ANDROID_NDK_VERSION} \
  && export JAVA_HOME=/usr/lib/jvm/java-8-openjdk-amd64 \
  && export PATH=$JAVA_HOME/bin:${ANDROID_SDK_ROOT}/tools:${ANDROID_SDK_ROOT}/tools/bin:${ANDROID_SDK_ROOT}/platform-tools:${PATH} \
  \
  # install openJDK 8
  && apt-get update -qq \
  && apt-get install -qq -y --no-install-recommends software-properties-common \
  && add-apt-repository ppa:openjdk-r/ppa \
  && apt-get update -qq \
  && apt-get install -qq -y --no-install-recommends unzip openjdk-8-jdk \
  \
  # Download Android SDK commandline tools
  && mkdir -p ${ANDROID_SDK_ROOT} \
  && chown -R 777 ${ANDROID_INSTALL_LOCATION} \
  && wget -q https://dl.google.com/android/repository/sdk-tools-linux-4333796.zip -O /tmp/android-sdk.zip \
  && unzip -q /tmp/android-sdk.zip -d ${ANDROID_SDK_ROOT} \
  \
  # Install platform tools and NDK
  && yes | sdkmanager \
    "platform-tools" \
    "ndk;${ANDROID_NDK_VERSION}" \
    "build-tools;${ANDROID_BUILD_TOOLS_VERSION}" \
    "platforms;android-${ANDROID_PLATFORM_VERSION}" \
    > /dev/null \
  \
  # Accept licenses
  && yes | sdkmanager --licenses \
  \
  && apt-get clean \
  && rm -rf /var/lib/apt/lists/* \
  && rm -rf /tmp/* \
  \
  # Update alias 'unity-editor'
  && { \
    echo '#!/bin/bash'; \
    echo "export ANDROID_INSTALL_LOCATION=${ANDROID_INSTALL_LOCATION}"; \
    echo "export ANDROID_SDK_ROOT=${ANDROID_SDK_ROOT}"; \
    echo "export ANDROID_HOME=${ANDROID_HOME}"; \
    echo "export ANDROID_NDK_HOME=${ANDROID_NDK_HOME}"; \
    echo "export JAVA_HOME=${JAVA_HOME}"; \
    echo "export PATH=${PATH}"; \
    echo 'xvfb-run -ae /dev/stdout "$UNITY_PATH/Editor/Unity" -batchmode "$@"'; \
  } > /usr/bin/unity-editor \
  && chmod +x /usr/bin/unity-editor
```

**Considered alternatives**

**Additional details**

- Thanks to @GabLeRoux (https://gitlab.com/gableroux/unity3d) !
- [`Limitations` section in document](https://game.ci/docs/game-ci/docker-images) says:
> Android builds for 2019.2 or lower will require you to roll your own images. This process will require you to manually specify NDK/SDK locations.
  - However, Android module for legacy Unity (especially 2018.4 LTS) still have (small) needs
- In my repo, The build test completed successfully
  - https://github.com/mob-sakai/docker/actions/runs/503115953
  - IL2CPP script backend uses NDK
  - Android SDK, NDK and tools has been installed on `2019.1-android` and `2019.2-android`

**Comment by webbertakken** [comment]
I'm not sure how accurate this is. As each version of unity editor dictates it's own SDK and NDK version. We never ended up having a tight versioning strategy for all these different SDKs and NDKs which are dictated by the unity version but not installed by the Unity Hub.

These images are in fact based on the lessons learned from that very unity3d repository by @GabLeRoux.

While they may build successfully, the reason why we didn't support android versions <= 2019.2 is that we could not find a reliable source of truth for which versions of android NDK/SDK were used.

Can we speak for how accurate these versions are? Because if they're different  versions than Unity originally intended, it will become a pain to maintain (again).

**Comment by GabLeRoux** [comment]
💯

**Comment by mob-sakai** [comment]
There is not much detailed information in Unity manual.
https://docs.unity3d.com/Manual/android-sdksetup.html

<br><br>

### Building for Android

Three development kits and tools are required to build for Android.

- JDK
- SDK Tools
- NDK (for IL2CPP scripting backend)

The required optional tools (platforms, platform-tools, build-tools) will be installed automatically at build time.

<br><br>

### For Unity 2019.1 and 2019.2

We can install recommended Android NDK/SDK (and OpenJDK) via UnityHub.
![](https://user-images.githubusercontent.com/12690315/105577266-c0368c80-5dbb-11eb-8328-777c2de561d9.png)

We can check it with the following command:

```sh
UNITY_VERSION=2019.1.14f1
docker run --rm unityci/editor:$UNITY_VERSION-android-0 find /opt/unity/Editor/Data/PlaybackEngines/AndroidPlayer -name 'OpenJDK' -type d
docker run --rm unityci/editor:$UNITY_VERSION-android-0 find /opt/unity/Editor/Data/PlaybackEngines/AndroidPlayer -name 'SDK' -type d
docker run --rm unityci/editor:$UNITY_VERSION-android-0 find /opt/unity/Editor/Data/PlaybackEngines/AndroidPlayer -name 'NDK' -type d
docker run --rm unityci/editor:$UNITY_VERSION-android-0 cat /opt/unity/Editor/Data/modules.json | jq ' .[] | select(.description | contains("Android")) | {title:.description, url:.downloadUrl }'

#################
#    RESULTS    #
#################
/opt/unity/Editor/Data/PlaybackEngines/AndroidPlayer/Tools/OpenJDK
/opt/unity/Editor/Data/PlaybackEngines/AndroidPlayer/SDK
/opt/unity/Editor/Data/PlaybackEngines/AndroidPlayer/NDK
{
  "title": "Allows building your Unity projects for the Android platform",
  "url": "https://download.unity3d.com/download_unity/148b5891095a/MacEditorTargetInstaller/UnitySetup-Android-Support-for-Editor-2019.1.14f1.pkg"
}
{
  "title": "Android SDK & NDK Tools 26.1.1",
  "url": "https://dl.google.com/android/repository/sdk-tools-darwin-4333796.zip"
}
{
  "title": "Android SDK Platform Tools 28.0.1",
  "url": "https://dl.google.com/android/repository/platform-tools_r28.0.1-darwin.zip"
}
{
  "title": "Android SDK Build Tools 28.0.3",
  "url": "https://dl.google.com/android/repository/build-tools_r28.0.3-macosx.zip"
}
{
  "title": "Android SDK Platforms 28",
  "url": "https://dl.google.com/android/repository/platform-28_r06.zip"
}
{
  "title": "Android NDK r16b",
  "url": "https://dl.google.com/android/repository/android-ndk-r16b-darwin-x86_64.zip"
}
```

<br><br>

### For Unity 2018.3 and 2018.4

OpenJDK 8 is included in Android module and the versions of the Android NDK/SDK is hard-coded.
We can check the versions with the following command:

```sh
UNITY_VERSION=2018.4.30f1
docker run -v "$(pwd)":/home --rm unityci/editor:$UNITY_VERSION-android-0 cp \
  /opt/unity/Editor/Data/PlaybackEngines/AndroidPlayer/UnityEditor.Android.Extensions.dll \
  /home/UnityEditor.Android.Extensions.dll

mkdir -p UnityEditor.Android.Extensions_$UNITY_VERSION
ilspycmd -p -o UnityEditor.Android.Extensions_$UNITY_VERSION UnityEditor.Android.Extensions.dll

echo '==== Find JDK version from Android module'
docker run --rm unityci/editor:$UNITY_VERSION-android-0 grep \
  'JAVA_VERSION' /opt/unity/Editor/Data/PlaybackEngines/AndroidPlayer/Tools/OpenJDK/Linux/release
echo '==== Find SDK versions from source code'
grep -r -e 'AndroidSDK.*Version.* = .*[0-9]' UnityEditor.Android.Extensions_$UNITY_VERSION
echo '==== Find NDK version from source code'
grep -r 'Version k_PackageRevision' UnityEditor.Android.Extensions_$UNITY_VERSION


#################
#    RESULTS    #
#################
==== Find JDK version from Android module
JAVA_VERSION="1.8.0"
==== Find SDK version from source codeUnityEditor.Android.Extensions_2018.4.30f1/UnityEditor.Android.PostProcessor.Tasks/CheckAndroidSDK.cs:
          public const int kMinAndroidSDKToolsVersion = 24;
UnityEditor.Android.Extensions_2018.4.30f1/UnityEditor.Android.PostProcessor.Tasks/CheckAndroidSDK.cs:
          public const string kMinAndroidSDKToolsVersionForApkzlib = "26.1.1";
UnityEditor.Android.Extensions_2018.4.30f1/UnityEditor.Android.PostProcessor.Tasks/CheckAndroidSDK.cs:
          public const string kMinAndroidSDKBuildToolsVersion = "28.0.3";
UnityEditor.Android.Extensions_2018.4.30f1/UnityEditor.Android.PostProcessor.Tasks/CheckAndroidSDK.cs:
          public const int kMinAndroidSDKPlatformToolsVersion = 23;
UnityEditor.Android.Extensions_2018.4.30f1/UnityEditor.Android.PostProcessor.Tasks/CheckAndroidSDK.cs:
          public const int kMinAndroidSDKPlatformVersion = 26;
==== Find NDK version from source code
UnityEditor.Android.Extensions_2018.3.14f1/UnityEditor.Android/AndroidNDKRoot.cs:
    private static readonly Version k_PackageRevision = new Version(16, 1, 4479499);
```

<br><br>

### Results

✅ : Installed, :x: : Not installed

| Unity       | SDK<br>Tools | NDK            | OpenJDK    |
| ----------- | ------------ | -------------- | ---------- |
| 2018.3.14f1 | ❌ 26.1.1     | ❌ 16.1.4479499 | ✅ 8 (=1.8) |
| 2018.4.30f1 | ❌ 26.1.1     | ❌ 16.1.4479499 | ✅ 8 (=1.8) |
| 2019.1.14f1 | ✅ 26.1.1     | ✅ 16.1.4479499 | ✅ 8 (=1.8) |
| 2019.2.21f1 | ✅ 26.1.1     | ✅ 16.1.4479499 | ✅ 8 (=1.8) |
| 2019.3.15f1 | ✅ 26.1.1     | ✅ 19.0.5232133 | ✅ 8 (=1.8) |
| 2019.4.18f1 | ✅ 26.1.1     | ✅ 19.0.5232133 | ✅ 8 (=1.8) |

<br><br>

### Conclusions

- Checked the required SDK/NDK by `module.json` and decompilation
- For 2018.x, the minimum requirements are `sdk-tool;26.1.1` and `ndk;16.1.44794`
- For 2019.x, no additional tools are required

**Comment by mob-sakai** [comment]
- Android module in Unity 2019.1 or earlier contains OpenJDK for Windows and Mac.
  - Removing these will reduce the image size by 368MB
- Android module in Unity 2019.1 has duplicate OpenJDKs
  - Removing these will reduce the image size by 484MB
- In Unity 2018.x, we can pre-install `platform-tools` and `build-tools;28.0.3` as following:
```
yes | sdkmanager "platform-tools" "build-tools;28.0.3"
```
- Download url for Android SDK Tools 26.1.1 is https://dl.google.com/android/repository/sdk-tools-darwin-4333796.zip

**Comment by mob-sakai** [comment]
I created a pull request for this issue.

**Comment by mob-sakai** [comment]
If you are interested: A workflow to check the required/installed version of Android SDK/NDK
https://github.com/mob-sakai/docker/blob/test/android_test/.github/workflows/check-android-sdk-ndk-versions.yml
