### ISSUE TITLE
Test results for 0.9.0 editor images (android-2019.2.0f1 exit code 134)

### ISSUE THREAD

**Issue by mob-sakai** [game-ci/docker#76]
### Description

I ran tests for all `0.9.0` editor images.

[The test project][https://github.com/mob-sakai/docker/tree/main/reference-project-test]:
- The default packages (for the installed Unity version) will be installed.
- `IL2CPP` will be selected as backend scripting (except for `base`, `windows-mono` and `mac-mono`).
- Contains empty tests for `playmode` and `editmode`.

|Category|Action|Description|
|--|--|--|
|Build|`unity-builder@main`|Build an empty scene. |
|Test|`unity-test-runner@main`|`all` test mode. |

### Results

[The test workflows](https://github.com/mob-sakai/docker/blob/main/.github/workflows/test-all.yml) have been dispatched as follows:
- Test All ✅(Run manually. Find all 0.9.0 editor image tags in DockerHub and dispatch the test workflows for each modules.): [Result][ta]
  - (dispatch) -> Test All ✅ (base, [2018.3.1f1, 2018.3.2f1, ...]): [Result][base]
  - (dispatch) -> Test All ❌ (linux-il2cpp, [2018.3.1f1, 2018.3.2f1, ...]): [Result][il2cpp]
  - (dispatch) -> Test All ✅ (windows-mono, [2018.3.1f1, 2018.3.2f1, ...]): [Result][windows]
  - (dispatch) -> Test All ✅ (mac-mono, [2018.3.1f1, 2018.3.2f1, ...]): [Result][mac]
  - (dispatch) -> Test All ❌ (android, [2018.3.1f1, 2018.3.2f1, ...]): [Result][android]
  - (dispatch) -> Test All ✅ (ios, [2018.3.1f1, 2018.3.2f1, ...]): [Result][ios]
  - (dispatch) -> Test All ✅ (webgl, [2018.3.1f1, 2018.3.2f1, ...]): [Result][webgl]

[ta]: https://github.com/mob-sakai/docker/actions/runs/553854994
[base]: https://github.com/mob-sakai/docker/actions/runs/553855590
[il2cpp]: https://github.com/mob-sakai/docker/actions/runs/553855591
[windows]: https://github.com/mob-sakai/docker/actions/runs/553855600
[mac]: https://github.com/mob-sakai/docker/actions/runs/553855598
[android]: https://github.com/mob-sakai/docker/actions/runs/553855604
[ios]: https://github.com/mob-sakai/docker/actions/runs/553855647
[webgl]: https://github.com/mob-sakai/docker/actions/runs/553855588

### Failures

|Module|Version|Cause|Fixed|
|--|--|--|--|
|android|2019.2.0f1|[exit code: 134][android_2019.2.0f1]||
|linux-il2cpp|2019.3.0f6|[il2cpp.exe did not run properly. unknown arguments: --sysroot-path=/][il2cpp_2019.3.0f6]|#78|
|linux-il2cpp|2019.3.1f1|[il2cpp.exe did not run properly. unknown arguments: --sysroot-path=/][il2cpp_2019.3.1f1]|#78|
|linux-il2cpp|2019.3.2f1|[il2cpp.exe did not run properly. unknown arguments: --sysroot-path=/][il2cpp_2019.3.2f1]|#78|
|linux-il2cpp|2019.3.3f1|[il2cpp.exe did not run properly. unknown arguments: --sysroot-path=/][il2cpp_2019.3.3f1]|#78|
|linux-il2cpp|2019.3.4f1|[il2cpp.exe did not run properly. unknown arguments: --sysroot-path=/][il2cpp_2019.3.4f1]|#78|
|linux-il2cpp|2019.3.5f1|[il2cpp.exe did not run properly. unknown arguments: --sysroot-path=/][il2cpp_2019.3.5f1]|#78|
|linux-il2cpp|2019.4.0f1|[C++ code builder is unable to build C++ code for Linux:<br>Could not find valid clang executable at clang][il2cpp_2019.4.0f1]|#78|

[android_2019.2.0f1]: https://github.com/mob-sakai/docker/runs/1869399495?check_suite_focus=true#step:5:799
[il2cpp_2019.3.0f6]: 
https://github.com/mob-sakai/docker/runs/1869397837?check_suite_focus=true#step:4:3593
[il2cpp_2019.3.1f1]: 
https://github.com/mob-sakai/docker/runs/1869398009?check_suite_focus=true#step:4:3593
[il2cpp_2019.3.2f1]: https://github.com/mob-sakai/docker/runs/1869398032?check_suite_focus=true#step:4:3592
[il2cpp_2019.3.3f1]: https://github.com/mob-sakai/docker/runs/1869398047?check_suite_focus=true#step:4:3592
[il2cpp_2019.3.4f1]: https://github.com/mob-sakai/docker/runs/1869398061?check_suite_focus=true#step:4:3592
[il2cpp_2019.3.5f1]: https://github.com/mob-sakai/docker/runs/1869398082?check_suite_focus=true#step:4:3591
[il2cpp_2019.4.0f1]: https://github.com/mob-sakai/docker/runs/1869398161?check_suite_focus=true#step:4:3620

Do we need to fix or ignore the failed image?

### Note

- This test results **DO NOT** guarantee that the 'successful' image supports all use cases.
- [The `2018.2.x` images has been created](https://hub.docker.com/r/unityci/editor/tags?page=1&ordering=last_updated&name=2018.2) but [be ignored for test.](https://github.com/mob-sakai/docker/blob/main/.github/workflows/test-all.yml#L43)

**Comment by davidmfinol** [comment]
Since these are all older versions (<=2019.4.0f1), we can probably ignore these? We can put a comment on https://game.ci/docs/game-ci/docker-images#older-versions-of-unity, saying we support versions > 2019.4.0f1.

**Comment by webbertakken** [comment]
As for this repo we're providing docker images, which I would argue is a bit more universal than CI specifically. Therefor I would not drop support for <= 2019.4.0f1. 

However it looks like all errors are in early patch levels of new minor releases (all starting from `0f1` or `0f6`), and based on that I think it's perfectly acceptable to not fix these.

I do think it would be useful to keep a list of defects somewhere. This could be a nice addition to the UI of the versioning backend. If we were to be able to create an issue there and link it to certain builds as well as github issues, then we have it nicely documented.

**Comment by davidmfinol** [comment]
Since @mob-sakai fixed most of the failures listed here, should we close this issue and open a separate issue just for the android-2019.2.0f1 exit code: 134 error?
