### ISSUE TITLE
Server-less build system

### ISSUE THREAD

**Issue by mob-sakai** [game-ci/docker#83]
The build workflows will be triggered from [the versioning-backend server](https://github.com/game-ci/versioning-backend).
However, most of the functionality can be replaced by GitHub Actions.

I propose a **Server-less build system**.

## Summary

['Build All' workflow](https://github.com/mob-sakai/docker/blob/main/.github/workflows/build-all.yml)
['Build Editor' workflow](https://github.com/mob-sakai/docker/blob/main/.github/workflows/build-editor.yml)

- Add workflows to build images without the versioning-backend server.
- Check out latest release and build `base` and `hub`.
  - The existed image tag building will be skipped.
  - Use `skopeo` to check for the existence of tags.
- After `base` and `hub` images are built, the workflow to build the editor image will be dispatched (on a per-module basis for readability).
  - Build All (build base and hub)
    - (dispatch) -> Build Editor (base, [2018.3.1f1, 2018.3.2f1, ...])
    - (dispatch) -> Build Editor (linux-il2cpp, [2018.3.1f1, 2018.3.2f1, ...])
    ...
    - (dispatch) -> Build Editor (webgl, [2018.3.1f1, 2018.3.2f1, ...])
- This workflow lists the available Unity versions without the versioning-backend server.
  - Use `unity-changeset` to get the available Unity versions.
  - As workflow settings, we can specify the minimum Unity version and the excluded Unity versions/module and alpha/beta support.
- The build workflows for a new release takes about a day.
  - If no new build is needed, it will take about 5 minutes.
- This workflow will run daily to build for new released Unity versions or to rebuild.
  - If other build workflows ('Build All' or 'Build Editor') are in progress or queued, this workflow will be skipped.
    - It prevents workflow congestion.
  - 'Build Editor' workflow may fail with a timeout, but in most cases the rebuild will succeed.

## For example

| Trigger | base/hub image | base (=linux) | linux-il2cpp | windows-mono | mac-mono | android | ios | webgl |
| -- | -- | -- | -- | -- | -- | -- | -- | -- |
| Release<br>v0.9 | [✅ (147 Unity versions found)][ba1] | [✅ 147][base1] | [✅ 147][il2cpp1] | [✅ 147][windows1] | [✅ 145 ❌ 2][mac1] | [✅ 142 ❌ 5][android1] | [✅ 145 ❌ 2][ios1] | [✅ 139 ❌ 8][webgl1] |
| Scheduled<br>(rebuild) | [✅ (150 Unity versions found)][ba2] | [✅ 3][base2] | [✅ 3][il2cpp2] | [✅ 3][windows2] | [✅ 5][mac2] | [✅ 8][android2] | [✅ 5][ios2] | [✅ 11][webgl2] |
| Scheduled<br>(rebuild) | [✅ (150 Unity versions found)][ba3] | - | - | - | - | - | - | - |

- In the 1st run after the release, several builds failed due to timeouts and bandwidth limitations.
- In the 2nd run, not only the failed versions but also the newly released versions (2019.4.20f1, 2020.2.4f1, 2021.1.0b6) were built and published.
- In the 3rd run, all versions had already been released. So there were no additional builds.
- Published images: https://hub.docker.com/repository/docker/mobsakai/unity_editor
  - Supported versions: 2018.3 or later (2021.1 beta included)

[ba1]: https://github.com/mob-sakai/docker/actions/runs/550301363
[base1]: https://github.com/mob-sakai/docker/actions/runs/550303251
[il2cpp1]: https://github.com/mob-sakai/docker/actions/runs/550303278
[windows1]: https://github.com/mob-sakai/docker/actions/runs/550303671
[mac1]: https://github.com/mob-sakai/docker/actions/runs/550303282
[android1]: https://github.com/mob-sakai/docker/actions/runs/550303206
[ios1]: https://github.com/mob-sakai/docker/actions/runs/550303238
[webgl1]: https://github.com/mob-sakai/docker/actions/runs/550303333

[ba2]: https://github.com/mob-sakai/docker/actions/runs/564810681
[base2]: https://github.com/mob-sakai/docker/actions/runs/564812375
[il2cpp2]: https://github.com/mob-sakai/docker/actions/runs/564812619
[windows2]: https://github.com/mob-sakai/docker/actions/runs/564812457
[mac2]: https://github.com/mob-sakai/docker/actions/runs/564812321
[android2]: https://github.com/mob-sakai/docker/actions/runs/564812348
[ios2]: https://github.com/mob-sakai/docker/actions/runs/564812372
[webgl2]: https://github.com/mob-sakai/docker/actions/runs/564812388

[ba3]: https://github.com/mob-sakai/docker/actions/runs/566999381

**Comment by webbertakken** [comment]
Note that the backend is already based on cloud functions (serverless), but I'm assuming that's not what you meant.

There is a lot more to the versioning backend than scheduling builds.

Firstly there are several triggers:

- Tagging docker repo (as you mentioned)
- Unity creates a new release
- Unity changes an older release
- Retry after fix without having to rebuild all images (with is about 1TB).

Only these would be hard to cover in actions only.

Then there are several functionalities unique to a programmable backend:

- Easily accessible information about all the builds and when they were modified
- Reporting new builds to discord
- Reporting failures or other useful information in the alert channel (for maintainers)
- Retrying failed builds (currently we retry 14 times for a total of 15 tries)

And what we want to add in the near future:

- Display a list of all available images and using search engine in some frontend
- Inspecting specific failures and having a user friendly (admin) interface for retrying builds
- Adding notes for specific builds, to keep track of per-version caveats

Therefor I do not think it is a good idea to create a very complex actions workflow.

**Comment by mob-sakai** [comment]
I understood.
To be frank, I just wanted a "customizable" build workflow for myself (for #50). :smile:

**Comment by webbertakken** [comment]
I could give you admin access to the project if you like, so you could reproduce code changes?
