### ISSUE TITLE
Some additional environment variables

### ISSUE THREAD

**Issue by dominicmarmionswrve** [game-ci/docker#84]
**Context**
We are migrating from gableroux docker images on circleci.

**Suggested solution**
Could you please add the following environment variables on images similar to `unityci/editor:ubuntu-2019.4.14f1-android-0.9.0`?
1. `export JAVA_HOME=/opt/unity/Editor/Data/PlaybackEngines/AndroidPlayer/OpenJDK`
2. `export ANDROID_HOME=/opt/unity/Editor/Data/PlaybackEngines/AndroidPlayer/SDK`
3. `export ANDROID_NDK_HOME=/opt/unity/Editor/Data/PlaybackEngines/AndroidPlayer/NDK`
4. `export PATH=$JAVA_HOME/bin:$ANDROID_HOME/tools:$ANDROID_HOME/tools/bin:$ANDROID_HOME/platform-tools:$PATH`

Also, could you run the following to accept latest android tool updates: `yes | $ANDROID_HOME/tools/bin/sdkmanager --licenses || true`

**Considered alternatives**
Also worth considering, could you either change `UNITY_PATH` environment variable
from: `/opt/unity`
to: `/opt/unity/Editor/Unity`
Or alternatively create a new environment variable for this.

**Additional details**
We can set these ourselves in our own yml builds but it might useful for others.

Thanks!

**Comment by webbertakken** [comment]
Could you please elaborate on the rationale behind these changes?

Please assume I don't know anything about the inner workings of Unity editor.
We're willing to add each line if there's a sound rationale behind it.

Also note that some of these paths may not really exist on images other than those with `android` as a target platform.

**Comment by dominicmarmionswrve** [comment]
No problem. Yeah, the java ones are for android target platforms.

We build a unity sdk that leverages native code on android which is coded in java. To build the unity android app we need to compile (and run tests) on the native android layer, which then gets packaged into unity, and then we build/package the whole lot together.

**Comment by chrishultin** [comment]
This might also increase general reliability for Android builds.

Quick details of each var:
`JAVA_HOME` - Canonical way to specify system path to Java JRE/JDK
`ANDROID_HOME` - Canonical way to specify system path to Android SDK
`ANDROID_NDK_HOME` - Canonical way to specify Android NDK path

The `PATH` env var should also be updated to add all the Android command-line utilities to the default search path, to facilitate usage of those tools in pre- or post-Unity build steps.

**Comment by chrishultin** [comment]
@dominicmarmionswrve Check out https://github.com/game-ci/docker/pull/88 - just merged, should set those environment variables for you.  You might still need to accept the license agreement on your own, though.

**Comment by webbertakken** [comment]
We might still wanna accept the license for the sdk manager, as we're making images for CI, and the license has been accepted on peoples computers already.

I recently [excluded](https://github.com/game-ci/docker/pull/87/files) 2018.2 builds and below from using this fix because sdkmanager was not recognized. Perhaps we should undo the change using your suggestion:

```
yes | $ANDROID_HOME/tools/bin/sdkmanager --licenses
```

We could then apply it to both 2018 and 2019+ images.
