### ISSUE TITLE
No Unity 2020.2.5f1 docker image

### ISSUE THREAD

**Issue by kreghek** [game-ci/docker#85]
**Context**

I want to use this image. Because old Unity version don't works correctly with `com.unity.localization` package. Updating of Unity to latest is one of suggestions from Unity Team. https://forum.unity.com/threads/troubleshooting-addressables-issues.1060346/

I want to avoid version degradation to 2019. May be new version solve my problem with localization.

**Suggested solution**

Please, deploy this version to docker hub to use it from GH Actions.

**Considered alternatives**

**Additional details**

I have failed build here https://github.com/kreghek/Zilon_Roguelike/runs/1933651478?check_suite_focus=true
There is my build config https://github.com/kreghek/Zilon_Roguelike/blob/fix-997-localization-recreate-2/.github/workflows/activation.yml

**Comment by basdp** [comment]
+1. Also, 2020.2.6f1 is out for a few days. Is the automated system broken? The readme states that new versions should be added automatically after a few hours.

**Comment by webbertakken** [comment]
See my answer here https://github.com/game-ci/docker/issues/79

**Comment by webbertakken** [comment]
It's [running](http://localhost:3000/docs/docker/versions).

![image](https://user-images.githubusercontent.com/20756439/109435566-5e50ee80-7a1b-11eb-834f-1e5ade14b433.png)

Closing this issue. Thanks for bringing it up!
