### ISSUE TITLE
Cannot find 'uname' in 2019.4.22f1

### ISSUE THREAD

**Issue by davidmfinol** [game-ci/docker#96]
**Bug description**
WebGL and LinuxIL2CPP builds fail:
[Error:  FATAL UNHANDLED EXCEPTION: System.AggregateException: One or more errors occurred. ---> System.ComponentModel.Win32Exception: ApplicationName='uname', CommandLine='-s', CurrentDirectory='', Native error= Cannot find the specified file](https://github.com/finol-digital/Card-Game-Simulator/runs/2128701947?check_suite_focus=true#step:5:11652)

**How to reproduce**
Run Unity Builder after upgrading project version to 2019.4.22f1, which simultaneously adds `"com.unity.toolchain.win-x86_64-linux-x86_64": "0.1.19-preview",` to the dependencies in `Packages/manifest.json`.

**Expected behavior**
Build should succeed.

**Additional details**
Previous build before the upgrade succeeded: https://github.com/finol-digital/Card-Game-Simulator/actions/runs/660126123
Then the build failed when the only change was upgrading from 2019.4.20f1 to 2019.4.22f1: https://github.com/finol-digital/Card-Game-Simulator/actions/runs/660302653

**Comment by davidmfinol** [comment]
Seems to be a duplicate of https://github.com/game-ci/docker/issues/92
I tried clearing the cache, but got more errors.
I believe this is an environment issue with GitHub Actions, as my Android builds also failed with `/usr/bin/env: ‘sh’: No such file or directory`
I'll try again tomorrow to see if the issue clears.

**Comment by davidmfinol** [comment]
Solution: Replace `com.unity.toolchain.win-x86_64-linux-x86_64` with `com.unity.toolchain.linux-x86_64`

For context, it seems that upgrading to 2019.4.22f1 requires using the new package described at https://forum.unity.com/threads/linux-il2cpp-cross-compiler-packages-now-available-in-preview.975693/
Since I did the upgrade on a windows machine, Unity automatically added `com.unity.toolchain.win-x86_64-linux-x86_64` to the project dependencies. But using that package instead of  `com.unity.toolchain.linux-x86_64` does not work on Linux. 
The easiest solution is likely to make the upgrade on a Linux machine; otherwise, you have to manually edit both `Packages/manifest.json` and `Packages/packages-lock.json`

**Comment by webbertakken** [comment]
Do I understand correctly that this is effectively a breaking change in Unity?

**Comment by davidmfinol** [comment]
It can be a breaking change depending on the upgrade path. If you upgrade from an older 2019.4 LTS release to the latest 2019.4 LTS on a Windows machine, that will break Unity Builder LinuxIL2CPP and WebGL builds.
The workaround is mentioned above.

**Comment by webbertakken** [comment]
But isn't the real problem that it's 

NOT a package that resolves different for different host platforms

But separate packages with the same goal, but different for each platform, that are not cross platform compatible?

If you upgrade from a Linux machine, can your colleagues on Windows no longer work with the project?

**Comment by davidmfinol** [comment]
It is a problem that there's multiple packages instead of just one, but it's a problem that's easy enough to workaround. 
With the workaround I mentioned, you can still collaborate between Linux and Windows PCs, though it does remove the ability to make Linux IL2CPP builds on a Windows PC.

As a fix on the Unity Builder side, we could maybe add some logic that will check which package is being used for Linux IL2CPP and WebGL builds, and make a temporary change to use the correct dependency during the build.
