### ISSUE TITLE
[MacOS] Cannot build Android using 2020.3.0f1 image

### ISSUE THREAD

**Issue by SilkyPantsDan** [game-ci/docker#99]
**Bug description**
Building example project via Docker image fails

**How to reproduce**

- Clone/Download example project repo
- Update `ci/docker_build.sh` as needed to build locally
- Run `ci/docker_build.sh` with image `'unityci/editor:ubuntu-2020.3.0f1-android-0.11.0`

**Expected behavior**
Android should build a debug APK

**Additional details**

It seems to fail with this exception

```
Picked up JAVA_TOOL_OPTIONS: -Dfile.encoding=UTF-8
AAPT2 aapt2-3.6.0-6040484-linux Daemon #3: Idle daemon unexpectedly exit. This should not happen.
Note: /project/Temp/gradleOut/unityLibrary/src/main/java/com/unity3d/player/UnityPlayerActivity.java uses or overrides a deprecated API.
Note: Recompile with -Xlint:deprecation for details.

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':launcher:processReleaseResources'.
> A failure occurred while executing com.android.build.gradle.internal.tasks.Workers$ActionFacade
   > AAPT2 aapt2-3.6.0-6040484-linux Daemon #2: Unexpected error during link, attempting to stop daemon.
     This should not happen under normal circumstances, please file an issue if it does.
```

Full log available here: https://pastebin.com/nm3Wman3

**Comment by SilkyPantsDan** [comment]
On further investigation - this may be a MacOS specific issue. I was able to run the same project fine under Ubuntu with docker, but not under Big Sur with docker  `Docker version 20.10.5, build 55c4c88`

**Comment by webbertakken** [comment]
This is the very first image in the 2020.3 range. Generally I'd recommend moving on to a more stable version (like the latest 2020.3.x version). There are sometimes more reports for the `0f1` versions not working for unexplainable reasons.

If it is indeed a MacOS issue, and the error mentions linux daemon then I do not think there is much we can do from our side.

Closing this issue until we have more specific information that is somehow actionable or explains the bug indeed being in our docker images.

**Comment by SilkyPantsDan** [comment]
I'll update here if I do find anything concrete
